"""make_position_entry_order_nullable

Revision ID: 902d38f5fe96
Revises: 002
Create Date: 2025-12-18 14:14:42.090877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '902d38f5fe96'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_index('ix_signals_market_id', table_name='signals')
    op.drop_index('ix_signals_status', table_name='signals')
    op.drop_index('ix_signals_strategy_name', table_name='signals')
    op.drop_table('signals')
    op.drop_table('paper_balances')
    op.drop_index('ix_executor_orders_created_at', table_name='executor_orders')
    op.drop_index('ix_executor_orders_signal_id', table_name='executor_orders')
    op.drop_index('ix_executor_orders_status', table_name='executor_orders')
    op.drop_table('executor_orders')
    op.drop_index('ix_strategy_states_strategy_name', table_name='strategy_states')
    op.drop_table('strategy_states')
    op.drop_index('ix_positions_created_at', table_name='positions')
    op.drop_index('ix_positions_market_id', table_name='positions')
    op.drop_index('ix_positions_status', table_name='positions')
    op.drop_index('ix_positions_strategy_name', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_executor_trades_order_id', table_name='executor_trades')
    op.drop_index('ix_executor_trades_position_id', table_name='executor_trades')
    op.drop_index('ix_executor_trades_timestamp', table_name='executor_trades')
    op.drop_table('executor_trades')
    op.alter_column('markets', 'tracking_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_markets_tier_active', table_name='markets')
    op.drop_index('ix_snapshots_market_timestamp', table_name='snapshots')
    op.drop_index('ix_trades_market_timestamp', table_name='trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trades_market_timestamp', 'trades', ['market_id', 'timestamp'], unique=False)
    op.create_index('ix_snapshots_market_timestamp', 'snapshots', ['market_id', 'timestamp'], unique=False)
    op.create_index('ix_markets_tier_active', 'markets', ['tier', 'active'], unique=False)
    op.alter_column('markets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'tracking_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('executor_trades',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_paper', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('size_shares', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('size_usd', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('fee_usd', sa.NUMERIC(precision=20, scale=6), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('polymarket_trade_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['executor_orders.id'], name='executor_trades_order_id_fkey'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='executor_trades_position_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='executor_trades_pkey')
    )
    op.create_index('ix_executor_trades_timestamp', 'executor_trades', ['timestamp'], unique=False)
    op.create_index('ix_executor_trades_position_id', 'executor_trades', ['position_id'], unique=False)
    op.create_index('ix_executor_trades_order_id', 'executor_trades', ['order_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_paper', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('market_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('entry_order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('size_shares', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('cost_basis', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('unrealized_pnl_pct', sa.NUMERIC(precision=10, scale=6), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('realized_pnl', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('hedge_position_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_hedge', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('close_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_order_id'], ['executor_orders.id'], name='positions_entry_order_id_fkey'),
    sa.ForeignKeyConstraint(['hedge_position_id'], ['positions.id'], name='positions_hedge_position_id_fkey'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name='positions_market_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='positions_pkey')
    )
    op.create_index('ix_positions_strategy_name', 'positions', ['strategy_name'], unique=False)
    op.create_index('ix_positions_status', 'positions', ['status'], unique=False)
    op.create_index('ix_positions_market_id', 'positions', ['market_id'], unique=False)
    op.create_index('ix_positions_created_at', 'positions', ['created_at'], unique=False)
    op.create_table('strategy_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('last_scan_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('markets_scanned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_signals', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_trades', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('winning_trades', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('losing_trades', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_pnl', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('best_trade_pnl', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('worst_trade_pnl', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='strategy_states_pkey')
    )
    op.create_index('ix_strategy_states_strategy_name', 'strategy_states', ['strategy_name'], unique=True)
    op.create_table('executor_orders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('signal_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_paper', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('limit_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('executed_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('size_usd', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('size_shares', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('filled_shares', sa.NUMERIC(precision=20, scale=6), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('polymarket_order_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('filled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name='executor_orders_signal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='executor_orders_pkey')
    )
    op.create_index('ix_executor_orders_status', 'executor_orders', ['status'], unique=False)
    op.create_index('ix_executor_orders_signal_id', 'executor_orders', ['signal_id'], unique=False)
    op.create_index('ix_executor_orders_created_at', 'executor_orders', ['created_at'], unique=False)
    op.create_table('paper_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('balance_usd', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'10000'::numeric"), autoincrement=False, nullable=False),
    sa.Column('starting_balance_usd', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'10000'::numeric"), autoincrement=False, nullable=False),
    sa.Column('high_water_mark', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'10000'::numeric"), autoincrement=False, nullable=False),
    sa.Column('low_water_mark', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'10000'::numeric"), autoincrement=False, nullable=False),
    sa.Column('total_pnl', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='paper_balances_pkey')
    )
    op.create_table('signals',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('market_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('edge', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('price_at_signal', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('best_bid', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('best_ask', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('suggested_size_usd', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name='signals_market_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='signals_pkey')
    )
    op.create_index('ix_signals_strategy_name', 'signals', ['strategy_name'], unique=False)
    op.create_index('ix_signals_status', 'signals', ['status'], unique=False)
    op.create_index('ix_signals_market_id', 'signals', ['market_id'], unique=False)
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    # ### end Alembic commands ###
